spring.application.name=gestione-esami
server.port=23110
spring.datasource.url=jdbc:postgresql://localhost:5433/esami_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=esami_user
spring.datasource.password=esami_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# JWT - Chiave pubblica RSA di Mauro
spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:public.pem