apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestione-esami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestione-esami
  template:
    metadata:
      labels:
        app: gestione-esami
    spec:
      containers:
        - name: gestione-esami
          image: gestione-esami:latest
          ports:
            - containerPort: 23110
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: db-name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: db-password
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: guest
            - name: RABBITMQ_PASSWORD
              value: guest
